# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript sources
RUN npm run build

# Expose port if needed (optional) 
# EXPOSE 3000

# Start the MCP server
CMD ["node", "build/index.js"]
